sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '6'
before_install:
  - npm i -g npm@^3.9.3
before_script:
  - npm prune
  - npm run build
after_success:
  - npm run build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
